default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ins_development

test:
  <<: *default
  database: ins_test

production:
  <<: *default
  database: ins_production
  username: ins
  password: <%= ENV['INS_DATABASE_PASSWORD'] %>
